# index:
#     path: /
#     controller: App\Controller\IndexController::index

hello:
  resource: '../src/Resources/config'
  type: directory

app:
  path: /
  controller: App\Controller\AppController::home
